# Generated by Django 4.0.4 on 2022-05-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('repetitions', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
