# Generated by Django 4.0.4 on 2022-05-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('arms', models.FloatField()),
                ('waist', models.FloatField()),
                ('hips', models.FloatField()),
                ('thighs', models.FloatField()),
            ],
        ),
    ]
