# Generated by Django 4.0.4 on 2022-05-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
