export const GET_PLANS = 'GET_PLANS'
export const DELETE_PLANS = 'DELETE_PLANS'
export const CREATE_PLAN = 'CREATE_PLAN'
export const EDIT_PLAN = 'EDIT_PLAN'
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
